### ISSUE TITLE
The UCE metric of the scratch model

### ISSUE THREAD

**Issue by huangchaoxing** [ExplainableML/BayesCap#6]
Hi, 
You mentioned that the err term in the UCE is computed between the reference (y) and the output of the frozen network(\hat{y}). I am wondering if you compute the err term in the UCE for the scratch model in the above way, or you compute  the scratch model's  err term  by using the reference  map and the output from the scratch model.

Thank you so much.

**Comment by udion** [comment]
Could you please rephrase the question? I did not understand it.

**Comment by huangchaoxing** [comment]
> Could you please rephrase the question? I did not understand it.


In page 8 of the paper, you compute the err(Bm) term in the UCE by computing the L2 norm between the reference image and the output of the frozen network. However, it is also mentioned that the scratch model does not have access to the frozen model. So did you use the reference image and the output of the scratch model to compute the err(Bm) term in the UCE of the scratch model ?

Thank u.

**Comment by udion** [comment]
You need to compute the error ***between the model's prediction and the ground truth*** for the UCE.

If your model is "scratch" model, then, of course, one has to compute the error between its output and ground truth.

For more details on UCE, see this: https://proceedings.mlr.press/v121/laves20a.html
